version: "3.9"
services:

  express_frontend:
    build:
      context: ./services/express_frontend
    ports:
      - "3000:3000"

  django_platform:
    name: django_platform
    build:
      context: ./services/django_platform
    ports:
      - "8000:8000"